Citizen.CreateThread(function()
    AddTextEntry('105gt', 'Alfa Romeo 105 GT')
    AddTextEntry('124spider', '124Spider')
    AddTextEntry('155q4', 'AR155 Q4')
    AddTextEntry('16challenger', 'Challenger')
    AddTextEntry('17m760i', 'BMW M60i')
    AddTextEntry('180sx', 'AR180 SX')
    AddTextEntry('18PERFORMANTE', 'Lamborghini Perfomante')
    AddTextEntry('19s650', 'Mercedes-Benz Maybach S650')
    AddTextEntry('2015s3', 'Audi S3')
    AddTextEntry('2017chiron', 'Bugatti Chrion')
    AddTextEntry('212expo51', 'Ferrari 212 Export')
    AddTextEntry('3000gt', 'Mitsubishi 3000 GT')
    AddTextEntry('348s', 'Ferrari 348')
    AddTextEntry('350zrb', 'Nissan 350ZR')
    AddTextEntry('356ac', 'Porsche 356 Cabrio')
    AddTextEntry('370z', 'Nissan 370Z')
    AddTextEntry('412', 'Ferrari 412')
    AddTextEntry('440i', 'BMW 440i')
    AddTextEntry('4881', 'Ferrari 488')
    AddTextEntry('4c', 'Alfa Romeo 4C')
    AddTextEntry('500gtrlam', 'Lamborghini GTR')
    AddTextEntry('575m', 'Ferrari 575m')
    AddTextEntry('600sel', 'Mercedes-Benz 600 SEL')
    AddTextEntry('635', 'BMW 635')
    AddTextEntry('675lt', 'McLaren 675LT')
    AddTextEntry('69charger', 'Dodge Charger R/T')
    AddTextEntry('718b', 'Porsche 718')
    AddTextEntry('718boxster', 'Porsche 718 Boxster S')
    AddTextEntry('718caymans', 'Porsche 718 Cayman S')
    AddTextEntry('720s', 'McLaren 720S')
    AddTextEntry('750li', 'BMW 750LI')
    AddTextEntry('850csi', 'BMW E31')
    AddTextEntry('8cs', 'Alfa Romeo 8C')
    AddTextEntry('911r', 'Porsche 911R')
    AddTextEntry('911tbs', 'Porsche 911 TBS')
    AddTextEntry('911turbos', 'Porsche 911 Turbo S')
    AddTextEntry('968', 'Porsche 968 Turbo S')
    AddTextEntry('992c', 'Porsche 992 Carrera S')
    AddTextEntry('a6fnbodykit', 'Audi A6 Avant Breitbau')
    AddTextEntry('a6tfsi', 'Audi A6 Limousine')
    AddTextEntry('a8audi', 'Audi A8')
    AddTextEntry('a8fsi', 'Audi A8 FSI')
    AddTextEntry('aaq4', 'Audi A4 TFSI')
    AddTextEntry('agerars', 'Koenigsegg Agera RS')
    AddTextEntry('alfa67', 'Alfa Romeo 33 Stradale')
    AddTextEntry('amggt', 'Mercedes-Benz AMG GT')
    AddTextEntry('amggtr', 'Mercedes-Benz AMG GTR')
    AddTextEntry('asterion', 'Lamborghini Asterion')
    AddTextEntry('audis8om', 'Audi S8')
    AddTextEntry('auds5', 'Audi S5')
    AddTextEntry('b63s', 'Mercedes-Benz Brabrus B63S')
    AddTextEntry('bbentayga', 'Bentley Bentayga')
    AddTextEntry('bdivo', 'Bugatti Divo')
    AddTextEntry('bmci', 'BMW M5')
    AddTextEntry('bmm', 'Bentley Mulsanne')
    AddTextEntry('bmwe34', 'BMW E34')
    AddTextEntry('bmwe65', 'BMW E65')
    AddTextEntry('bmws', 'BMW S1000R')
    AddTextEntry('boss302', 'Ford Mustang B302')
    AddTextEntry('boss429', 'Ford Mustang B429')
    AddTextEntry('brabus700', 'Mercedes-Benz Brabus G63 AMG')
    AddTextEntry('brabus850', 'Mercedes-Benz Brabus 850 Coupe')
    AddTextEntry('c5rs6', 'Audi C5 RS6')
    AddTextEntry('c63w205', 'Mercedes-Benz AMG C63s')
    AddTextEntry('camry18', 'Toyota Camry XSE')
    AddTextEntry('camry55', 'Toyota Camry')
    AddTextEntry('cayenneturbo', 'Porsche Cayenne Turbo')
    AddTextEntry('ccx', 'Koenigsegg CCX')
    AddTextEntry('celica', 'Toyota Celica')
    AddTextEntry('cla45sb', 'Mercedes-Benz AMG CLA 45')
    AddTextEntry('contgt2011', 'Bentley Continental GT')
    AddTextEntry('cortina', 'Ford Cortina MK1')
    AddTextEntry('Lamborghini Countach', 'count6')
    AddTextEntry('e21', 'BMW E21')
    AddTextEntry('Mercedes-Benz E400', 'e400')
    AddTextEntry('e60', 'BMW M5 E60')
    AddTextEntry('e63amg', 'Mercedes-Benz AMG E63')
    AddTextEntry('evo10', 'Mitsubishi Evo X')
    AddTextEntry('evo9mr', 'Mitsubishi EVO9')
    AddTextEntry('f60', 'Ferrari F60')
    AddTextEntry('f812', 'Ferrari 812')
    AddTextEntry('fer612', 'Ferrari 612 Scaglietti')
    AddTextEntry('g65amg', 'Mercedes-Benz AMG G65')
    AddTextEntry('gencoupe', 'Honda Genesis Coupe')
    AddTextEntry('giuliasuper', 'Alfa Romeo Giulia Super')
    AddTextEntry('gl63', 'Mercedes-Benz AMG GL63')
    AddTextEntry('gt86', 'Toyota GT')
    AddTextEntry('gt86lb', 'Toyota GT LB')
    AddTextEntry('gtr', 'Nissan Nismo GTR')
    AddTextEntry('gtr2020', 'Nissan GTR 2020')
    AddTextEntry('i8', 'BMW I8')
    AddTextEntry('impala', 'Dodge Impala')
    AddTextEntry('jes', 'Koenigsegg Jester')
    AddTextEntry('KoenigseggAgeraR', 'Koenigsegg Agera R')
    AddTextEntry('lhgt3', 'Lamborghini Pegassi')
    AddTextEntry('lp610', 'Lamborghini LP610')
    AddTextEntry('lp670sv', 'Lamborghini LP670 SV')
    AddTextEntry('lp700', 'Lamborghini LP700')
    AddTextEntry('lp770', 'Lamborghini LP770')
    AddTextEntry('m2', 'BMW M2')
    AddTextEntry('m3e30', 'BMW M3 E30')
    AddTextEntry('m3e46', 'BMW M3 E46')
    AddTextEntry('m3f80', 'BMW M3 F80')
    AddTextEntry('m4f82', 'BMW M4 F82')
    AddTextEntry('m5f90', 'BMW M5 F90')
    AddTextEntry('m6f13', 'BMW M6 F13')
    AddTextEntry('macan', 'Porsche Macan')
    AddTextEntry('mb300sl', 'Mercedes-Benz 300 SL')
    AddTextEntry('mers63c', 'Mercedes-Benz S63C')
    AddTextEntry('mgrantur2010', 'Maserati Grantur 2010')
    AddTextEntry('mgt', 'Ford Mustang GT')
    AddTextEntry('mig', 'Ferrari MIG')
    AddTextEntry('mlmansory', 'Maserati Mansory ML')
    AddTextEntry('modena', 'Ferrari 360 Modena')
    AddTextEntry('monza', 'Ferrari Monza')
    AddTextEntry('mst', 'Ford Mustang MST')
    AddTextEntry('nisaltima', 'Nissan Altima V6')
    AddTextEntry('nismo20', 'Nissan Nismo 20 GTR')
    AddTextEntry('nissantitan17', 'Nissan Titan 17')
    AddTextEntry('ody18', 'Honda ODY18')
    AddTextEntry('oldm6', 'BMW M6 (o)')
    AddTextEntry('panamera17turbo', 'Porsche Panamera 17T')
    AddTextEntry('patroly60', 'Nissan Rancher X1')
    AddTextEntry('pista', 'Ferrari Pista')
    AddTextEntry('pruf', 'Porsche RGT 8 GT3')
    AddTextEntry('q7', 'Audi Q7')
    AddTextEntry('q820', 'Audi Q8')
    AddTextEntry('qashqai16', 'Nissan Qashqai 16')
    AddTextEntry('rmodmustang', 'Ford Mustang GT RM')
    AddTextEntry('rmodsian', 'Lamborghini Sian')
    AddTextEntry('rmodveneno', 'Lamborghini Veneno')
    AddTextEntry('rmodx6', 'BMW X6')
    AddTextEntry('rrphantom', 'Rolls Royce Phantom')
    AddTextEntry('rrst', 'Range Rover R12')
    AddTextEntry('Audi RS3', 'rs3')
    AddTextEntry('rs5r', 'Audi RS5')
    AddTextEntry('rsrs4avant', 'Audi RS4 Avant')
    AddTextEntry('s3sedan', 'Audi A3 Limousine')
    AddTextEntry('s500w222', 'Mercedes-Benz S500')
    AddTextEntry('s600w220', 'Mercedes-Benz S600')
    AddTextEntry('senna', 'McLaren Senna')
    AddTextEntry('skyline', 'Nissan Skyline')
    AddTextEntry('srt8', 'Jeep SRT8')
    AddTextEntry('superduty', 'Ford SD')
    AddTextEntry('svr16', 'Rang Rover SVR')
    AddTextEntry('taycan', 'Porsche Taycan')
    AddTextEntry('trhawk', 'Jeep Hawk')
    AddTextEntry('tz3', 'Alfa Romeo TZ3')
    AddTextEntry('urus', 'Lamborghini Urus')
    AddTextEntry('v250', 'Mercedes-Benz v250')
    AddTextEntry('wraith', 'Rolly Royce Wraith')
    AddTextEntry('x5e53', 'BMW X5')
    AddTextEntry('x6m', 'BMW X6M')
    AddTextEntry('z4bmw', 'BMW Z4')

    AddTextEntry('bentayga17', 'Bentley Bentayga 17')
    AddTextEntry('gt2rs', 'Porsche GT2RS')
    AddTextEntry('gt3rs', 'Porsche GT3RS')
    AddTextEntry('750il', 'BMW 750IL')
    AddTextEntry('750il', 'BMW 750IL')
    AddTextEntry('e63s', 'Mercedes-Benz E63S')
    AddTextEntry('rmodlp770', 'Lamborghini LP770')
    AddTextEntry('488nlargo', 'Ferrari 488')
    AddTextEntry('sl65bs', 'Mercedes-Benz SL65')
    AddTextEntry('fpacehamann', 'Jaguar F-Pace')
    AddTextEntry('amggt63s', 'Mercedes-Benz AMG GT63S')
    AddTextEntry('rs3', 'Audi RS3')
    AddTextEntry('gt', 'Bentley Continental GT')
    AddTextEntry('gmt900escalade', 'Cadilac Escalade GMT900')
    AddTextEntry('gmt900escal', 'Cadilac Escalade GMT900')
    AddTextEntry('cl65', 'Mercedes-Benz CL65')
    AddTextEntry('db1117', 'Aston Martin DB1117')
    AddTextEntry('cullinan 20', 'Rolls Royce Cullinan 20')
    AddTextEntry('escalade', 'Cadilac Escalade 2015')
    AddTextEntry('gl 63 amg', 'Mercedes-Benz GL63AMG')
    AddTextEntry('mqgts', 'Maserati Quattroporte')
    AddTextEntry('ef9 civic', 'Honda Civic EF9')
    AddTextEntry('ferrari pis', 'Ferrari PIS')
    AddTextEntry('992t', 'Porsche 992t')
    AddTextEntry('rmodgt63', 'Mercedes-Benz AMG GT63 (2)')
    AddTextEntry('dawnonyx', 'Rolls Royce Dawn Onyx')
    AddTextEntry('18performan', 'Lamborghini 18 Performante')
    AddTextEntry('p1', 'McLaren P1')
    AddTextEntry('amggtrr20', 'Mercedes-Benz AMG GTR20')
    AddTextEntry('s63c217', 'Mercedes-Benz S63AMG')
    AddTextEntry('mc63', 'Mercedes-Benz C63 (old)')
    AddTextEntry('s65amg', 'Mercedes-Benz S65AMG')
    AddTextEntry('pgt3', 'Porsche GT3')
    AddTextEntry('dawn', 'Rolls Royce Dawn')
    AddTextEntry('rmodpagani', 'Pagani ')
    AddTextEntry('chall70', 'Dodge Challanger 70')
    AddTextEntry('s63c217', 'Mercedes-Benz S63AMG Coupe')
    AddTextEntry('evo9', 'Mitsubishi Evo9')
    AddTextEntry('me63', 'Mercedes-Benz E63S AMG (old)')
    AddTextEntry('650s', 'McLaren 650S')
    AddTextEntry('pgt3', 'Porsche GT3')
    AddTextEntry('corvette', 'Corvette LSPD')
    AddTextEntry('valor19silv', 'Siverado 19 Marked')
    AddTextEntry('freetahoe', 'Chevy Tahoe 19 Unmarked')
    AddTextEntry('valor16fpiu', 'Ford Explorer 16 Marked')
    AddTextEntry('valor14char', 'Dodge Charger 14 Marked')
    AddTextEntry('teslax', 'Tesla Model X')
    AddTextEntry('ghispo2', 'Maserati Ghibli Marked')
    AddTextEntry('unmarked2', 'Dodge Charger Unmarked')
    AddTextEntry('f12ber', 'Ferrari F12 Marked')
    AddTextEntry('swathel', 'SWAT Helikopter')
    AddTextEntry('718', 'Porsche 718 Marked')
    AddTextEntry('c8cop', 'Corvette C8 Unmarked')
    AddTextEntry('sahpins', 'BlackBetty')
    AddTextEntry('eqc400', 'Mercedes-Benz EQC400')
    AddTextEntry('valor18taho', 'Chevy Tahoe 18 Marked')
    AddTextEntry('mocpack', 'Police Truck - Command')
    AddTextEntry('bmwm5', 'BMW M5 Unmarked')
    AddTextEntry('models', 'Tesla Model S')
    AddTextEntry('f450towtruk', 'F450 TOW')
    AddTextEntry('210507p', 'Lada Police Marked')
    AddTextEntry('pd8', 'Chevy Tahoe Unmarked (schrott)')
    AddTextEntry('sr650fly', 'Sea Ray 650 fly')
    AddTextEntry('', '')
    AddTextEntry('', '')
    AddTextEntry('', '')
    AddTextEntry('', '')



    end)
